import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, Bug, ExternalLink, FileWarning, ShieldAlert } from 'lucide-react';
import { SITE_URL, localizedAlternates } from '@/lib/site';
import type { Locale } from '@/lib/i18n';

const content = {
  ko: { title: '오류 및 번역 문제 신고', description: '개인정보를 보내지 않고 재현 가능한 오류를 신고하는 방법입니다.', back: '게임 목록으로', notice: '공개 GitHub Issues에서 번역 및 사이트 오류를 접수합니다. 아래 정보를 텍스트로 작성해 주세요.', action: 'GitHub Issues에서 신고하기', privacy: '트레이너 실행 파일, 저장 파일, 비밀번호, 이메일, 계정 정보 등 개인정보나 실행 파일 자체는 첨부하지 마세요. 신고 내용은 공개될 수 있습니다.', items: [['페이지 정보', '문제가 발생한 페이지 URL, 표시 언어, 게임 이름을 기록합니다.'], ['버전과 문구', '트레이너의 정확한 버전과 잘못 표시된 원문·번역문을 텍스트로 기록합니다.'], ['재현 단계', '어떤 동작 뒤에 문제가 나타났는지 순서대로 적고, 브라우저 이름과 버전을 함께 기록합니다.']]},
  en: { title: 'Report a Translation or Site Issue', description: 'How to report a reproducible issue without sending personal data.', back: 'Back to games', notice: 'Translation and site issues are accepted through the public GitHub Issues page. Provide the details below as text.', action: 'Report on GitHub Issues', privacy: 'Do not attach trainer executables, save files, passwords, email addresses, account details, or other personal information. Reports may be public.', items: [['Page details', 'Record the affected page URL, display language, and game name.'], ['Version and wording', 'Record the exact trainer version and the incorrect source and translated text as plain text.'], ['Reproduction steps', 'List the actions that led to the issue and include the browser name and version.']]},
  ja: { title: '翻訳・サイトの問題を報告', description: '個人情報を送らず、再現可能な問題を報告する方法です。', back: 'ゲーム一覧へ', notice: '翻訳とサイトの問題は、公開GitHub Issuesで受け付けます。以下の情報をテキストで記載してください。', action: 'GitHub Issuesで報告', privacy: 'トレーナー実行ファイル、セーブファイル、パスワード、メールアドレス、アカウント情報などの個人情報を添付しないでください。報告内容は公開される場合があります。', items: [['ページ情報', '問題が発生したページのURL、表示言語、ゲーム名を記録します。'], ['バージョンと文言', 'トレーナーの正確なバージョンと、誤って表示された原文・翻訳文をテキストで記録します。'], ['再現手順', '問題が発生するまでの操作を順番に記載し、ブラウザ名とバージョンも記録します。']]},
} satisfies Record<Locale, { title: string; description: string; back: string; notice: string; action: string; privacy: string; items: [string, string][] }>;
const localeOf = (value: string): Locale => value === 'en' || value === 'ja' ? value : 'ko';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const current = localeOf((await params).locale); const page = content[current]; return { title: `${page.title} | LocalPatcher`, description: page.description, alternates: { canonical: `${SITE_URL}/${current}/contact`, languages: localizedAlternates('/contact') } }; }
export default async function ContactPage({ params }: { params: Promise<{ locale: string }> }) { const current = localeOf((await params).locale); const page = content[current]; const icons = [FileWarning, Bug, Bug]; return <main className="max-w-4xl mx-auto px-5 sm:px-6 py-10 md:py-14"><Link href={`/${current}`} className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-cyan-400"><ArrowLeft className="w-4 h-4" />{page.back}</Link><header className="my-10"><h1 className="text-3xl md:text-4xl font-bold text-white">{page.title}</h1><p className="mt-4 rounded-2xl border border-cyan-500/20 bg-cyan-950/20 p-5 text-sm leading-7 text-slate-300">{page.notice}</p><a href="https://github.com/wlrlxoj-bit/LocalPatcher/issues" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-400">{page.action}<ExternalLink className="w-4 h-4" /></a></header><div className="grid gap-5 md:grid-cols-3">{page.items.map(([title, text], index) => { const Icon = icons[index]; return <section key={title} className="rounded-2xl border border-slate-800 bg-slate-900/30 p-6"><Icon className="w-5 h-5 text-cyan-400" /><h2 className="mt-4 font-bold text-white">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></section>; })}</div><aside className="mt-8 flex gap-3 rounded-2xl border border-amber-500/20 bg-amber-950/10 p-5 text-sm leading-7 text-amber-100/80"><ShieldAlert className="mt-1 w-5 h-5 shrink-0 text-amber-400" /><p>{page.privacy}</p></aside></main>; }
