import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, BadgeCheck, Bot, Megaphone, RefreshCw } from 'lucide-react';
import { SITE_URL, localizedAlternates } from '@/lib/site';
import type { Locale } from '@/lib/i18n';

const content = {
  ko: { title: '편집 및 검수 정책', description: '번역 데이터의 수집, 검수, 버전 관리와 광고·제휴 공개 원칙입니다.', back: '게임 목록으로', intro: '등록되는 번역은 정확성과 출처 확인을 목표로 다음 절차에 따라 관리합니다.', sections: [['수집과 승인', '지원할 원본 트레이너의 버전과 문자열을 확인한 뒤 번역 초안을 수집합니다. 문맥, 단축키, 수치 표기를 검토하고 승인된 매핑만 서비스에 등록합니다.'], ['버전 일치 확인', '파일 크기와 SHA-256 해시는 등록된 빌드와의 일치 여부를 확인하는 수단입니다. 일치 여부는 파일의 안전성이나 제작자의 진위를 보증하지 않으며, 버전이 다르면 패치를 중단합니다.'], ['수정과 오류 처리', '오역, 누락, 잘못된 게임명 또는 버전 정보가 확인되면 해당 항목을 재검토하고 수정합니다. 재현에 필요한 게임명, 트레이너 버전, 화면의 문구를 오류 신고 페이지의 형식에 따라 알려 주세요.'], ['자동화와 수동 검토', '기계 번역이나 자동화 도구를 초안 작성과 비교에 사용할 수 있지만, 공개 전에는 사람이 문맥과 표기를 검토하는 것을 원칙으로 합니다. 검토가 완료되지 않은 결과를 승인된 번역으로 표시하지 않습니다.'], ['광고와 제휴', '서비스 운영을 위해 광고와 제휴 링크를 사용할 수 있습니다. 광고·제휴 관계는 번역 승인이나 평가에 영향을 주지 않으며, 가격과 외부 제공 내용은 해당 제공자의 조건을 따릅니다.']]},
  en: { title: 'Editorial and Review Policy', description: 'How translations are collected, reviewed, versioned, corrected, and separated from advertising.', back: 'Back to games', intro: 'Published translations are managed under the following process to improve accuracy and traceability.', sections: [['Collection and approval', 'We identify the supported original trainer build and source strings before collecting a translation draft. Context, shortcuts, and numeric notation are reviewed, and only approved mappings are registered.'], ['Version matching', 'File size and SHA-256 hashes only compare a file with a registered build. A match does not guarantee safety or authorship. Patching stops when the version does not match.'], ['Corrections and errors', 'Mistranslations, omissions, incorrect game names, and version errors are reviewed and corrected when confirmed. Use the issue-report format with the game, trainer version, and exact displayed wording needed to reproduce the problem.'], ['Automation and human review', 'Machine translation or automation may assist drafting and comparison, but a person should review context and terminology before publication. Unreviewed output is not presented as an approved translation.'], ['Advertising and affiliate disclosure', 'The service may use advertising and affiliate links to support operation. Commercial relationships do not control translation approval or evaluation; prices and external offers remain subject to each provider’s terms.']]},
  ja: { title: '編集・レビュー方針', description: '翻訳データの収集、確認、バージョン管理、訂正、広告・提携の開示方針です。', back: 'ゲーム一覧へ', intro: '公開する翻訳は、正確性と確認可能性を高めるため、次の手順で管理します。', sections: [['収集と承認', '対応する元トレーナーのバージョンと文字列を確認してから翻訳案を収集します。文脈、ショートカット、数値表記を確認し、承認された対応表のみ登録します。'], ['バージョンの一致', 'ファイルサイズとSHA-256ハッシュは登録済みビルドとの一致を比較する手段にすぎません。一致しても安全性や作者の真正性は保証されません。バージョンが一致しない場合は処理を中止します。'], ['訂正とエラー対応', '誤訳、欠落、誤ったゲーム名やバージョン情報が確認された場合は再確認して訂正します。ゲーム名、トレーナーのバージョン、画面に表示された文言を問題報告ページの形式でお知らせください。'], ['自動化と人による確認', '機械翻訳や自動化ツールを下書き・比較に利用する場合がありますが、公開前に人が文脈と用語を確認することを原則とします。未確認の出力を承認済み翻訳として表示しません。'], ['広告とアフィリエイト', '運営を支えるため広告やアフィリエイトリンクを使用する場合があります。商業上の関係は翻訳の承認や評価に影響せず、価格と外部提供内容には各提供者の条件が適用されます。']]},
} satisfies Record<Locale, { title: string; description: string; back: string; intro: string; sections: [string, string][] }>;
const localeOf = (value: string): Locale => value === 'en' || value === 'ja' ? value : 'ko';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const current = localeOf((await params).locale); const page = content[current]; return { title: `${page.title} | LocalPatcher`, description: page.description, alternates: { canonical: `${SITE_URL}/${current}/editorial-policy`, languages: localizedAlternates('/editorial-policy') } }; }
export default async function EditorialPolicyPage({ params }: { params: Promise<{ locale: string }> }) { const current = localeOf((await params).locale); const page = content[current]; const icons = [BadgeCheck, BadgeCheck, RefreshCw, Bot, Megaphone]; return <main className="max-w-4xl mx-auto px-5 sm:px-6 py-10 md:py-14"><Link href={`/${current}`} className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-cyan-400"><ArrowLeft className="w-4 h-4" />{page.back}</Link><header className="my-10"><h1 className="text-3xl md:text-4xl font-bold text-white">{page.title}</h1><p className="mt-4 text-slate-300 leading-relaxed">{page.intro}</p></header><div className="space-y-5">{page.sections.map(([title, text], index) => { const Icon = icons[index]; return <section key={title} className="rounded-2xl border border-slate-800 bg-slate-900/30 p-6"><div className="flex items-start gap-4"><Icon className="mt-0.5 w-5 h-5 shrink-0 text-cyan-400" /><div><h2 className="text-lg font-bold text-white">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></div></div></section>; })}</div></main>; }
